version: '3.8'

services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - HOST=0.0.0.0
    depends_on:
      - backend
    networks:
      - journal-network

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:mysql://db:3306/journalsystem
      - DB_USERNAME=journal_user
      - DB_PASSWORD=journal321
    depends_on:
      - db
    networks:
      - journal-network

  db:
    image: mysql:8.0.36
    environment:
      MYSQL_DATABASE: journalsystem
      MYSQL_USER: journal_user
      MYSQL_PASSWORD: journal321
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - journal-network

volumes:
  mysql_data:

networks:
  journal-network:
    driver: bridge
