apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-db-deployment
  template:
    metadata:
      labels:
        app: auth-db
    spec:
      containers:
        - name: auth-db
          image: mysql:8.0.36
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "rootpassword"
            - name: MYSQL_DATABASE
              value: "authentication"
            - name: MYSQL_USER
              value: "journal_user"
            - name: MYSQL_PASSWORD
              value: "journal321"
          ports:
            - containerPort: 3308  # Porten för MySQL-databasen

---

apiVersion: v1
kind: Service
metadata:
  name: auth-db-service
spec:
  selector:
    app: auth-db-deployment  # Matchar pods med denna label
  ports:
    - protocol: TCP
      port: 3308      # Tjänsten blir tillgänglig på denna port inom klustret
      targetPort: 3308 # Vidarebefordra till containerns port 3308
      nodePort: 30007  # Exponera tjänsten på denna port för externa anslutningar
  type: NodePort      # Gör tjänsten tillgänglig utanför klustret
