apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-db
  template:
    metadata:
      labels:
        app: auth-db
    spec:
      containers:
        - name: auth-db
          image: mysql:8.0.36
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "rootpassword"
            - name: MYSQL_DATABASE
              value: "authentication"
            - name: MYSQL_USER
              value: "journal_user"
            - name: MYSQL_PASSWORD
              value: "journal321"
            - name: MYSQL_TCP_PORT  # Anger den port MySQL lyssnar på
              value: "3308"
          ports:
            - containerPort: 3308  # Konfigurera porten

---

apiVersion: v1
kind: Service
metadata:
  name: auth-db-service
spec:
  selector:
    app: auth-db  # Matcha pods med denna label
  ports:
    - protocol: TCP
      port: 3308       # Tjänsten blir tillgänglig på denna port inom klustret
      targetPort: 3308  # Vidarebefordra till containerns port 3307
      nodePort: 30007  # Exponera tjänsten på denna port för externa anslutningar
  type: NodePort       # Gör tjänsten tillgänglig utanför klustret
