apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
        - name: authentication
          image: alany10/authentication:latest  # Din Docker-image för backend
          ports:
            - containerPort: 8081  # Applikationen lyssnar på denna port i containern

---

apiVersion: v1
kind: Service
metadata:
  name: authentication-service
spec:
  selector:
    app: authentication  # Matchar backend-poddarna
  ports:
    - protocol: TCP
      port: 8081         # Exponera tjänsten på port 80 för externa anrop
      targetPort: 8081  # Vidarebefordra till backend-appen som kör på port 8080
      nodePort: 30002   # Exponera tjänsten på en specifik NodePort (kan justeras)
  type: NodePort       # Gör tjänsten tillgänglig utanför klustret
