apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1  # Du kan öka detta om du vill köra fler instanser
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: alany10/frontend:latest  # Din Docker-image för frontend
          ports:
            - containerPort: 5173  # Porten på vilken frontend-applikationen körs

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend  # Matchar poddarna med labeln app: frontend
  ports:
    - protocol: TCP
      port: 5173         # Exponera tjänsten på port 8080 för externa anrop
      targetPort: 5173  # Vidarebefordra till backend-appen som kör på port 8080
      nodePort: 30000   # Exponera tjänsten på en specifik NodePort (kan justeras)
  type: NodePort       # Gör tjänsten tillgänglig utanför klustret
