apiVersion: apps/v1
kind: Deployment
metadata:
  name: image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image
  template:
    metadata:
      labels:
        app: image
    spec:
      containers:
        - name: image
          image: alany10/image:latest  # Din Docker-image för backend
          ports:
            - containerPort: 3000  # Applikationen lyssnar på denna port i containern

---

apiVersion: v1
kind: Service
metadata:
  name: image-service
spec:
  selector:
    app: image  # Matchar backend-poddarna
  ports:
    - protocol: TCP
      port: 3000         # Exponera tjänsten på port 80 för externa anrop
      targetPort: 3000  # Vidarebefordra till backend-appen som kör på port 8080
      nodePort: 30004   # Exponera tjänsten på en specifik NodePort (kan justeras)
  type: NodePort       # Gör tjänsten tillgänglig utanför klustret
