apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-db
  template:
    metadata:
      labels:
        app: image-db
    spec:
      containers:
        - name: image-db
          image: mysql:8.0.36
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "rootpassword"
            - name: MYSQL_DATABASE
              value: "image"
            - name: MYSQL_USER
              value: "journal_user"
            - name: MYSQL_PASSWORD
              value: "journal321"
            - name: MYSQL_TCP_PORT  # Anger den port MySQL lyssnar på
              value: "3310"
          ports:
            - containerPort: 3310  # Konfigurera porten

---

apiVersion: v1
kind: Service
metadata:
  name: image-db-service
spec:
  selector:
    app: image-db  # Matcha pods med denna label
  ports:
    - protocol: TCP
      port: 3310       # Tjänsten blir tillgänglig på denna port inom klustret
      targetPort: 3310  # Vidarebefordra till containerns port 3307
      nodePort: 30009  # Exponera tjänsten på denna port för externa anslutningar
  type: NodePort       # Gör tjänsten tillgänglig utanför klustret
