apiVersion: apps/v1
kind: Deployment
metadata:
  name: message
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message
  template:
    metadata:
      labels:
        app: message
    spec:
      containers:
        - name: message
          image: alany10/message:latest  # Din Docker-image för backend
          ports:
            - containerPort: 8082  # Applikationen lyssnar på denna port i containern

---

apiVersion: v1
kind: Service
metadata:
  name: message-service
spec:
  selector:
    app: message  # Matchar backend-poddarna
  ports:
    - protocol: TCP
      port: 8082         # Exponera tjänsten på port 80 för externa anrop
      targetPort: 8082  # Vidarebefordra till backend-appen som kör på port 8080
      nodePort: 30003   # Exponera tjänsten på en specifik NodePort (kan justeras)
  type: NodePort       # Gör tjänsten tillgänglig utanför klustret
