quarkus:
  http:
    port: 8083
    cors: true  # Aktivera CORS
    cors-origins: "*"  # Den domän som tillåts (Frontend URL)
    cors-methods: "GET, POST, PUT, DELETE, OPTIONS"  # Tillåt specifika HTTP-metoder
    cors-headers: "*"  # Tillåt specifika headers
    cors-exposed-headers: "Location"  # Exponera vissa headers till klienten
    cors-max-age: 3600  # Cache-tid för CORS-svar (1 timme)
  datasource:
    jdbc:
      url: jdbc:mysql://localhost:3307/backend
    username: journal_user
    password: journal321
    reactive:
      url: mysql://localhost:3307/backend
      username: journal_user
      password: journal321
  hibernate-orm:
    database:
      generation: update
    log:
      sql: true
    show-sql: true
